[build-system]
requires = [
    "hatchling",
    "hatch-vcs",
]
build-backend = "hatchling.build"

# Metadata ====================================================================
[project]
name = "xrt_toolkit"
dynamic = ["version"]
description = "Collection of utilities to compute X-Ray Transforms."
readme = "README.rst"
requires-python = ">= 3.10, < 3.14"
license = "MIT"
authors = [
    { name = "S. Kashani", email = "sepand@kashani.ch" },
]
classifiers = [
    "Topic :: Scientific/Engineering",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
urls.download = "https://github.com/SepandKashani/xrt_toolkit"
dependencies = [
    "array-api-compat",
    "drjit >= 1.0, < 2",
    "numpy >= 1.25, < 3",
    "packaging >= 24.2",
]

# Optional dependencies =======================================================
[project.optional-dependencies]
viz = [
    "graphviz >= 0.20, < 1",
    "matplotlib >= 3.10, < 4",
]
dev = [
    "hatch >= 1.14, < 2",
    "pre-commit >= 4.1, < 5",
    "pytest >= 8.3, < 9",
    "ruff >= 0.9, < 1",  # keep synced with .pre-commit-config.yaml
    "tox >= 4.24, < 5",
    # -----------------------
    "cupy-cuda12x >= 13.0, < 14",
    "jax >= 0.6, < 1",
    "torch >= 2, < 3",
]
all = [
    "xrt_toolkit[viz,dev]",
]

# Get version info from Git ===================================================
[tool.hatch.version]
source = "vcs"

# sdist/wheel config ==========================================================
[tool.hatch.build]
exclude = [
    "/dev",
    "/doc",
    "/src/xrt_toolkit_tests",
]
include = [
    "/src",
]
packages = [
    "src/xrt_toolkit",
]

# Ruff config =================================================================
[tool.ruff]
fix = true  # auto fixing
exclude = ["src/**/__init__.py"]

[tool.ruff.lint]
select = ["I"]  # import sorting

[tool.ruff.lint.pydocstyle]
convention = "numpy"
